name: Deploy to EKS with Helm

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ secrets.ECR_REGISTRY }}:latest" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: docker build -t $IMAGE_TAG ./backend

      - name: Push Docker image to ECR
        run: docker push $IMAGE_TAG

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Set Image Tag in Helm Chart
        run: |
          sed -i "s|REPLACE_IMAGE|$IMAGE_TAG|g" backend/charts/values.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install backend-release backend/charts/ \
            --namespace default \
            --create-namespace
